version: "3"
services:
  postgres-inventory:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres-inventory
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - 5433:5432
    environment:
         - POSTGRES_PASSWORD=root
         - POSTGRES_USER=postgres
         - POSTGRES_DB=inventory
    restart: unless-stopped

    
  inventory-app:
    image: inventory-api:latest
    network_mode: bridge
    container_name: inventory-app
    expose:
      - 8081
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - postgres-inventory
    links:
      - postgres-inventory
      
volumes:
  postgres-data: